# 基本语法和自动梯度计算

In [1]:
import torch

In [2]:
x = torch.empty(4, 3)

In [3]:
x

tensor([[2.7490e+20, 9.1041e-12, 2.8884e+12],
        [7.5338e+28, 1.4013e-45, 2.7178e-06],
        [6.4107e-10, 3.3234e-09, 0.0000e+00],
        [0.0000e+00, 1.1351e-43, 0.0000e+00]])

In [4]:
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
torch.ones(3, 1)

tensor([[1.],
        [1.],
        [1.]])

In [6]:
torch.rand(4, 2)

tensor([[0.9303, 0.4233],
        [0.6367, 0.9880],
        [0.3893, 0.4255],
        [0.5589, 0.9872]])

In [7]:
torch.randn(2, 2)

tensor([[-0.4191,  0.1245],
        [ 0.2963, -0.0368]])

In [9]:
torch.rand?

In [10]:
torch.zeros(4, 2, dtype=torch.long)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [11]:
torch.tensor([3, 3, 3])

tensor([3, 3, 3])

In [12]:
a = torch.ones(4)

In [13]:
a

tensor([1., 1., 1., 1.])

In [14]:
a.numpy()

array([1., 1., 1., 1.], dtype=float32)

In [15]:
import numpy as np

In [17]:
a = np.ones(4)

In [18]:
a

array([1., 1., 1., 1.])

In [19]:
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)


In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu"), torch.double)

tensor([[2.7490e+20, 1.0000e+00, 2.8884e+12],
        [7.5338e+28, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00]], device='cuda:0')
tensor([[2.7490e+20, 1.0000e+00, 2.8884e+12],
        [7.5338e+28, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00]]) torch.float64


In [21]:
# AutoGrad

In [22]:
x = torch.ones(2,2, requires_grad=True)

In [23]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [24]:
y = x + 2

In [25]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [26]:
y.grad_fn

In [27]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [54]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [55]:
y = x * x

In [51]:
gradients = torch.FloatTensor([[1.0,1.0],[1.0, 1.0]])

In [56]:
y

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)

In [52]:
y.backward(gradients)

In [53]:
x.grad

tensor([[6.5000, 6.5000],
        [6.5000, 6.5000]])

In [41]:
out.backward()

In [42]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# Gradients

https://stackoverflow.com/questions/43451125/pytorch-what-are-the-gradient-arguments

z = (x + 1) ^ 2

grad z / grad x = 2 * (x + 1)

In [57]:
x = torch.ones(2,2, requires_grad=True)

In [59]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [60]:
y = x + 1

In [61]:
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [62]:
z = y * y

In [63]:
z

tensor([[4., 4.],
        [4., 4.]], grad_fn=<MulBackward0>)

In [64]:
z.backward(torch.FloatTensor([[1.0,1.0],[1.0,1.0]]))

In [65]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [66]:
x.grad

tensor([[4., 4.],
        [4., 4.]])